source "https://rubygems.org"

gem "sinatra", "~> 1.4.0"
gem "coderay", "~> 1.1.1"
gem "resque", "~> 1.22.0"
gem "resque-status", "~> 0.5.0"
gem "sinatra-asset-pipeline", "~> 0.7.0"
gem "rake", "~> 10.0"
gem "sass", "~> 3.4.22"
gem "uglifier", "~> 2.7.1"
gem "grub"
gem "pry"
